-- NBA Integrity Guard Database Schema

-- Table: signal_logs
-- Stores all signals generated by the system
CREATE TABLE IF NOT EXISTS signal_logs (
    id SERIAL PRIMARY KEY,
    signal_type VARCHAR(50) NOT NULL,
    game_id VARCHAR(100),
    rigging_index DECIMAL(5,4),
    anomaly_score DECIMAL(5,4),
    metadata JSONB,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: twitter_data
-- Stores Twitter sentiment analysis results
CREATE TABLE IF NOT EXISTS twitter_data (
    id SERIAL PRIMARY KEY,
    game_id VARCHAR(100) NOT NULL,
    rigging_index DECIMAL(5,4) NOT NULL,
    tweet_count INTEGER NOT NULL,
    avg_sentiment DECIMAL(5,4) NOT NULL,
    sample_tweets JSONB,
    timestamp TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: market_data
-- Stores Polymarket market data and anomalies
CREATE TABLE IF NOT EXISTS market_data (
    id SERIAL PRIMARY KEY,
    market_id VARCHAR(100) NOT NULL,
    game_id VARCHAR(100) NOT NULL,
    yes_price DECIMAL(10,8) NOT NULL,
    no_price DECIMAL(10,8) NOT NULL,
    spread_bps INTEGER NOT NULL,
    liquidity DECIMAL(20,2) NOT NULL,
    anomaly_detected BOOLEAN DEFAULT FALSE,
    anomaly_score DECIMAL(5,4),
    timestamp TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: trades
-- Stores all trade executions
CREATE TABLE IF NOT EXISTS trades (
    id SERIAL PRIMARY KEY,
    trade_id VARCHAR(100) UNIQUE NOT NULL,
    signal_type VARCHAR(50) NOT NULL,
    action VARCHAR(20) NOT NULL,
    market_id VARCHAR(100) NOT NULL,
    game_id VARCHAR(100),
    amount DECIMAL(20,2) NOT NULL,
    estimated_payout DECIMAL(20,2),
    actual_payout DECIMAL(20,2),
    status VARCHAR(20) DEFAULT 'PENDING_EXECUTION',
    timestamp TIMESTAMP NOT NULL,
    executed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: distributions
-- Stores profit distribution records
CREATE TABLE IF NOT EXISTS distributions (
    id SERIAL PRIMARY KEY,
    trade_id VARCHAR(100) REFERENCES trades(trade_id),
    total_profit DECIMAL(20,2) NOT NULL,
    hedge_amount DECIMAL(20,2) NOT NULL,
    ops_fee DECIMAL(20,2) NOT NULL,
    user_reward DECIMAL(20,2) NOT NULL,
    tx_hash VARCHAR(100),
    status VARCHAR(20) DEFAULT 'PENDING',
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX idx_twitter_game_id ON twitter_data(game_id);
CREATE INDEX idx_twitter_timestamp ON twitter_data(timestamp);
CREATE INDEX idx_market_game_id ON market_data(game_id);
CREATE INDEX idx_market_timestamp ON market_data(timestamp);
CREATE INDEX idx_trades_status ON trades(status);
CREATE INDEX idx_trades_timestamp ON trades(timestamp);
CREATE INDEX idx_signal_timestamp ON signal_logs(timestamp);
